learning:
  step_size: 0.000005
  batch_size: 128
  num_iters: 50000
  decay_rate: 0.999
  weight_decay: 0.00001
data:
  num_samples: 50000
  noise_stddev: 0.1
display:
  refresh_rate: 5
mlp:
  num_hidden_layers: 6
  hidden_layer_width: 30